###Inventory
###get all inventory
GET http://localhost:3000/inventory

###create new product
POST http://localhost:3000/inventory HTTP/1.1
constent-type: application/json

{
    "productName": "",
        "price": "",
        "label": "",
        "category": "",
        "sizeOptions": "",
        "productId": "",
        "productImage": ""

}

###get single product
GET http://localhost:3000/inventory/{productId}

###delete inventory item
DELETE http://localhost:3000/inventory/{productId} HTTP/1.1

###edit inventory item
PUT http://localhost:3000/inventory/6605b308922386e05db88a93 HTTP/1.1
content-type: application/json

{
     "productName": "Eggs",
        "price": "2.45",
        "label": "",
        "category": "dairy",
        "sizeOptions": "1 dozen",
        "productId": "0001",
        "productImage": ""
}

#####Orders
###get order by id
GET http://localhost:3000/orders/{orderId}

###create order
POST http://localhost:3000/orders HTTP/1.1
content-type: application/json

{
   "userName": "",
    "items": [{
        "itemId": "",
        "name": "",
        "quantity": "",
        "price": ""
    },
    {
        "itemId": "",
        "name": "",
        "quantity": "",
        "price": ""
    }
    ],
    "orderTotal": "" 
}

###edit order
PUT http://localhost:3000/{orderId} HTTP/1.1
content-type: application/json

{
"userName": "CLennart",
    "items": [{
        "itemId": "660594d07efa1afc2f66eecb",
        "name": "Steak",
        "quantity": "10",
        "price": "12.68"
    },
    {
        "itemId": "660594d07efa1afc2f66eec9",
        "name": "Apples",
        "quantity": "3",
        "price": "1.45"
    }
    ],
    "orderTotal": "131.15"
}

#####Account
###get all accounts
GET http://localhost:3000/account

###create account
POST http://localhost:3000/account HTTP/1.1
content-type: application/json

{
     "firstName": "Charles",
        "lastName": "Marrok",
        "email": "Charlie@packHQ.com",
        "password": "BrotherWolf"
}

###account login

###account logout


###edit account
PUT http://localhost:3000/account/{username} HTTP/1.1
content-type: application/json

{
     "firstName": "Charles",
        "lastName": "Smith",
        "email": "Charlie@packHQ.com",
        "password": "BrotherWolf"
}

###delete account
DELETE http://localhost:3000/account/{username} HTTP/1.1


###Reviews
###create review
POST http://localhost:3000/reviews HTTP/1.1

###edit review
PUT http://localhost:3000/reviews/{reviewId} HTTP/1.1
content-type: application/json

{
        "userName": "KDaniels",
        "productName": "Lucky Charms",
        "productId": "0004",
        "reviewText": "Too dry"
    }

###delete review
DELETE http://localhost:3000/reviews/{reviewId} HTTP/1.1
